### ISSUE TITLE
Is there a clever reason why __floatdisf and __floatundisf are unimplemented?

### ISSUE THREAD

**Issue by ketsuban** [rust-lang-nursery/compiler-builtins#216]
Looking at the code it seems like they *should* be really easy - all the functions in this group use a dead-simple macro. Is it just that nobody got around to doing it, or are these functions special somehow (e.g. problems a la rust-lang/rust#10184)?

**Comment by kevinaboos** [comment]
I also need these functions, specifically `__floatundisf`. I'm happy to contribute them to this crate for x86_64, but currently I have no idea where to begin. If someone can point me in the right direction as to how to implement them, I can get started.

**Comment by alexcrichton** [comment]
Sure yeah! Currently we mostly just port the implementations from C in the `compiler-rt` project directly to Rust (then add some tests and such). You can find the `compiler-rt` intrinsics in `compiler-rt/lib/builtins` typically, and I normally grep around for the symbol name to find where it's defined

**Comment by Ketsuban** [comment]
Back when I first created this issue I forked the repo and [added these two intrinsics](https://github.com/Ketsuban/compiler-builtins/commit/4c412d273512b4623958a9adb4685b33ef32b1d0) using `__floatdidf` and `__floatundidf` as a template, purely to address my personal need. I didn't make a pull request because I was cognizant of the fact I was engaging in cargo-cult programming, but now there's eyes on this issue I'll make sure everyone knows about it even if only so someone can tell me I was doing it wrong and should feel bad.
